export const HOME_PATH = '/'
export const LOGIN_PATH = '/login'
export const USER_PATH = '/users'
export const USER_NEW_PATH = '/users/new'
export const USER_DETAIL_PATH = '/users/:id'
export const BOOK_PATH = '/books'
export const BOOK_NEW_PATH = '/books/new'
export const BOOK_DETAIL_PATH = '/books/:id'
export const ORDER_PATH = '/orders'
export const ORDER_DETAIL_PATH = '/orders/:id'

